#
#Makefile for VIRGO config driver and config kernel service
#

ccflags-y := -w -I/media/ka_shrinivaasan/cbddc062-a016-4828-8780-21bc64cef1e8/linux-4.13.3/include -DDEBUG

virgoconfig_driver-y := virgo_config.o

obj-m               += virgo_config.o
