#
# Makefile for virgo_open(),virgo_close(),virgo_read(),virgo_write() VIRGO filesystem client system calls testcase
#

all:
	#g++ -g -I/media/shrinivaasanka/0fc4d8a2-1c74-42b8-8099-9ef78d8c8ea2/home/kashrinivaasan/linux-4.1.5/include -I/media/shrinivaasanka/0fc4d8a2-1c74-42b8-8099-9ef78d8c8ea2/home/kashrinivaasan/linux-4.1.5/arch/x86/include/generated/uapi/asm test_virgo_filesystem.c -o test_virgo_filesystem
	g++ -g -I/media/shrinivaasanka/0fc4d8a2-1c74-42b8-8099-9ef78d8c8ea2/home/kashrinivaasan/linux-4.1.5/include test_virgo_filesystem.c -o test_virgo_filesystem
clean:
	rm test_virgo_filesystem
