#
# Makefile for Virgo virgo_clone() cloud client system call 
#

ccflags-y := -w -DDEBUG -DLINUX_KERNEL_4_x_x -DVIRGO_KTLS

#obj-m               += virgo_clone.o
obj-y               += virgo_clone.o
