#
#Makefile for VIRGO SATURN Driver Program Analysis 
#

COMPILER := g++

ccflags-y := -w -I/media/ka_shrinivaasan/cbddc062-a016-4828-8780-21bc64cef1e8/linux-4.13.3/include -DDEBUG

virgosaturn_program_analysis_driver-y := virgo_saturn_program_analysis.o

obj-m               += virgo_saturn_program_analysis.o
