#
#Makefile for VIRGO bakery driver and bakery kernel service
#

ccflags-y := -w -I/media/ka_shrinivaasan/cbddc062-a016-4828-8780-21bc64cef1e8/linux-4.10.3/include -DDEBUG

virgobakery_driver-y := virgo_bakery.o

obj-m               += virgo_bakery.o
