#
#Makefile for VIRGO Kernel Transport Layer Security
#

ccflags-y := -w -I/media/ka_shrinivaasan/cbddc062-a016-4828-8780-21bc64cef1e8/linux-4.13.3/include -DDEBUG

virgoktls_driver-y := virgo_ktls.o

obj-m               += virgo_ktls.o
