#
# Makefile for Virgo virgo_open(), virgo_read(), virgo_write() and virgo_close() cloud client system calls 
#

ccflags-y := -w -DDEBUG -DLINUX_KERNEL_4_x_x

#obj-m               += virgo_clone.o
obj-y               += virgo_fs.o
