#
#Makefile for VIRGO kernel_analytics driver and kernel_analytics kernel service
#

ccflags-y := -w -I/media/ka_shrinivaasan/cbddc062-a016-4828-8780-21bc64cef1e8/linux-4.10.3/include -DDEBUG

virgokernel_analytics_driver-y := virgo_kernel_analytics.o

obj-m               += virgo_kernel_analytics.o
