# Makefile for virgo_malloc(),virgo_set(),virgo_get(),virgo_free() VIRGO memorypooling client system calls testcase

all:
	g++ -m64 -march=x86-64 -g -I/media/ka_shrinivaasan/cbddc062-a016-4828-8780-21bc64cef1e8/linux-4.13.3/include test_virgo_malloc.c -o test_virgo_malloc
clean:
	rm test_virgo_malloc
