# Makefile for virgo_malloc(),virgo_set(),virgo_get(),virgo_free() VIRGO memorypooling client system calls testcase

all:
	#g++ -g -I/media/shrinivaasanka/0fc4d8a2-1c74-42b8-8099-9ef78d8c8ea2/home/kashrinivaasan/linux-4.1.5/include -I/media/shrinivaasanka/0fc4d8a2-1c74-42b8-8099-9ef78d8c8ea2/home/kashrinivaasan/linux-4.1.5/arch/x86/include/generated/uapi/asm test_virgo_malloc.c -o test_virgo_malloc
	g++ -g -I/media/shrinivaasanka/0fc4d8a2-1c74-42b8-8099-9ef78d8c8ea2/home/kashrinivaasan/linux-4.1.5/include test_virgo_malloc.c -o test_virgo_malloc
clean:
	rm test_virgo_malloc
