#
# Makefile for VIRGO cpupooling syscalls testcase
#

all:
	g++ -m64 -march=x86-64 -g -I/media/ka_shrinivaasan/cbddc062-a016-4828-8780-21bc64cef1e8/linux-4.10.3/include test_virgo_clone.c -o test_virgo_clone
clean:
	rm test_virgo_clone
