#
# Makefile for VIRGO cpupooling syscalls testcase
#

all:
	g++ -g -I/media/shrinivaasanka/0fc4d8a2-1c74-42b8-8099-9ef78d8c8ea2/home/kashrinivaasan/linux-4.1.5/include -I/media/shrinivaasanka/0fc4d8a2-1c74-42b8-8099-9ef78d8c8ea2/home/kashrinivaasan/linux-4.1.5/arch/x86/include/generated/uapi/asm test_virgo_clone.c -o test_virgo_clone
clean:
	rm test_virgo_clone
